### ISSUE TITLE
[1.0.4] Bundle size went up by 200 kb

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember-classic-decorator#24]
After installing `1.0.4` our build failed because the `vendor.js` file went up by almost 200 kb. I guess that's because of the `ember-data` dependency. We don't use `ember-data`. Why is it included in the bundle?

**Comment by pzuraq** [comment]
Ah, that was a mistake, that should have been a dev dep.

**Comment by rwjblue** [comment]
Looks like it was fixed by https://github.com/emberjs/ember-classic-decorator/pull/25, just needs a release now I think.

**Comment by pzuraq** [comment]
This should be fixed in v1.0.5, and I've unpublished v1.0.4 since that could definitely cause negative impacts. Thanks for catching this, again really sorry!

**Comment by boris-petrov** [comment]
Not a problem at all. Thank you for the quick fix and great support!
