### ISSUE TITLE
Ember 3.11 window.__CLASSIC_HAS_CONSTRUCTOR__.add is not a function

### ISSUE THREAD

**Issue by lowski** [emberjs/ember-classic-decorator#29]
I'm using Ember 3.11.1 and latest version of `ember-classic-decorator` (0.1.4) and I'm getting error during boot:

```
TypeError: window.__CLASSIC_HAS_CONSTRUCTOR__.add is not a function
```

From what I see `window.__CLASSIC_HAS_CONSTRUCTOR__` is a `WeakMap` which does not implement `add` function. Any idea what can be wrong?

**Comment by pzuraq** [comment]
The latest version is v1.0.5, and the issue should be solved on that version. Can you update and confirm?

**Comment by lowski** [comment]
@pzuraq thank you for quick reply!

1.0.5 is working fine. Sorry for false alarm - `npm update` didn't want to update to the add-on to `1.0.5`. It seemed that `npm` thought 1.0.4 was the latest version (and so did I 😉). `npm uninstall ember-classic-decorator && npm install ember-classic-decorator` solved the problem for me.
