### ISSUE TITLE
Does not adhere to targets.js

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember-classic-decorator#30]
Even with `ie11` in `targets.js`, ES6+ code is being generated - the `let` keyword is being used and `catch` without parentheses for example.

**Comment by pzuraq** [comment]
The code for this addon doesn't get transpiled, and it looks like a few usages of modern features slipped through, my bad 😔 

https://github.com/emberjs/ember-classic-decorator/blob/master/vendor/classic-decorator/index.js#L147

Will try to get a fix up soon

**Comment by boris-petrov** [comment]
@pzuraq - thanks. [This also seems to break Firefox 47.](https://github.com/emberjs/ember-classic-decorator/blob/master/vendor/classic-decorator/index.js#L154)
