### ISSUE TITLE
Observer conversion

### ISSUE THREAD

**Issue by skaterdav85** [emberjs/ember-classic-decorator#41]
Why does an observer get converted from this:

```js
doSomething: observer('a', function() {
  // ...		
})
```

into this:

```js
import { observes } from '@ember-decorators/object';

@observes('a')
doSomething() {
  // ...
}
```

instead of this?

```js
import { observer } from '@ember/object';

@observer('a')
doSomething() {
  // ...
}
```

This doesn't match with how CPs are converted.

**Comment by pzuraq** [comment]
Observers do not have a decorator form in Ember directly. Long term, the plan is to phase them out. Ember Decorators provides some support so people can migrate, but you should work on removing observers sooner rather than later.

**Comment by skaterdav85** [comment]
@pzuraq thank you!
