### ISSUE TITLE
Does not work with `ember-cli-deprecation-workflow` v2

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember-classic-decorator#74]
`ember-classic-decorator` replaces the `require` function [here](https://github.com/emberjs/ember-classic-decorator/blob/v2.0.0/vendor/classic-decorator/index.js#L152) and doesn't set other required things on it like `has`. This breaks at least `ember-cli-deprecation-workflow` v2 which uses it. A discussion around that can be found after [this comment](https://github.com/mixonic/ember-cli-deprecation-workflow/pull/118#issuecomment-873915801).

**Comment by gilest** [comment]
Pushed an attempted fix #75 

Would appreciate a review 👀  by a maintainer
